# Generated by Django 5.1.7 on 2025-03-30 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('theme', models.CharField(choices=[('positive', 'Positive / Bright'), ('sad', 'Sad / Darker')], default='positive', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('song_url', models.URLField(blank=True, max_length=500, null=True)),
                ('album_art_url', models.URLField(blank=True, max_length=500, null=True)),
                ('track_title', models.CharField(blank=True, max_length=150)),
                ('artist_name', models.CharField(blank=True, max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('date_text', models.CharField(blank=True, max_length=50)),
                ('rating_stars', models.IntegerField(default=0)),
                ('rating_text', models.CharField(blank=True, max_length=150)),
                ('venue_icon1', models.CharField(blank=True, max_length=10)),
                ('venue_icon2', models.CharField(blank=True, max_length=10)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
